# Generated by Django 4.0.1 on 2022-01-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('done', 'done'), ('new', 'new')], max_length=10)),
            ],
        ),
    ]
